// app/components/SidePanel.vue
<script setup lang="ts">
const { color, weight } = storeToRefs(useAppStore());
</script>

<template>
  <div class="sticky top-3 my-3 ml-3 h-[calc(100dvh-24px)] w-[340px]">
    <div class="flex h-full flex-col overflow-auto rounded-xl border bg-surface p-6">
      <h1 class="text-balance text-center text-xl font-black">
        Tints and Shades Generator
      </h1>
      <div class="mt-12 flex flex-col gap-8 pb-10">
        <ColorInput v-model="color" label="Hex Color" />
        <ColorWeight v-model="weight" />
        <AppearanceSettings />
      </div>

      <PanelFooter class="mt-auto border-t border-muted pt-2" />
    </div>
  </div>
</template>

// src/components/SidePanel/SidePanel.tsx
import { EditWeight } from './EditWeight/EditWeight'
import { EditColor } from './EditColor/EditColor'
import { PreviewSettings } from './PreviewSettings/PreviewSettings'
import { ScrollArea } from '@mantine/core'
import { SidePanelActions } from './SidePanelActions/SidePanelActions'

const SidePanel = () => {
  return (
    <nav className="flex h-screen w-full flex-col border-none border-zinc-700 md:w-80 md:border-r md:border-solid lg:w-96">
      <ScrollArea offsetScrollbars className="flex-1 px-5">
        <div className="py-4">
          <h1 className="text-center text-2xl font-black text-zinc-100">
            Tints and Shades
            <br />
            Generator
          </h1>
        </div>

        <div>
          <div className="flex flex-col gap-4">
            <section className="border-t border-zinc-600/60 pt-4">
              <EditColor />
            </section>
            <section>
              <EditWeight />
            </section>

            <section className="border-t border-zinc-600/60 pt-4">
              <PreviewSettings />
            </section>
          </div>
        </div>
      </ScrollArea>

      <div className="border-t border-zinc-700">
        <SidePanelActions />
      </div>
    </nav>
  )
}

export { SidePanel }
